### ISSUE TITLE
How to use this Library in Objecitve c

### ISSUE THREAD

**Issue by gopikrishnacse55** [alexruperez/SpeechRecognizerButton#1]

**Comment by alexruperez** [comment]
I have [updated to 0.1.7 with Swift 4.1 compatibility](https://github.com/alexruperez/SpeechRecognizerButton/commit/757558ee3a7e2efb66436112e30108be44ec19d9), but you only can fully use it in Swift and/or Interface Builder, but some properties and methods aren't exposed to Objective-C API.
