### ISSUE TITLE
Can we play this audio file after it was done?

### ISSUE THREAD

**Issue by thihaaung6245** [alexruperez/SpeechRecognizerButton#2]
Is there anyway that I can play the recorded audio file?

**Comment by alexruperez** [comment]
@thihaaung6245 of course, just call [play(updatingWaveform:)](https://github.com/alexruperez/SpeechRecognizerButton/blob/757558ee3a7e2efb66436112e30108be44ec19d9/SpeechRecognizerButton/SFButton.swift#L249) method, like in the [sample project](https://github.com/alexruperez/SpeechRecognizerButton/blob/757558ee3a7e2efb66436112e30108be44ec19d9/Example/ViewController.swift#L23). Thanks for using! 😃
