### ISSUE TITLE
Getting dictation not available error msg in iPad in iOS 12.1

### ISSUE THREAD

**Issue by meetdoshi1992** [alexruperez/SpeechRecognizerButton#4]
![attachment-2821250039738548008Screenshot-0503-110700](https://user-images.githubusercontent.com/7357932/57224351-cf453c00-7026-11e9-9dfb-cfbee4eced33.png)

Please see this image. I am Getting dictation not available error msg in iPad in iOS 12.1. And also I have checked that internet is connected properly. Still I am getting error msg.

Please let me know when this error comes and how to solve it.?

**Comment by alexruperez** [comment]
[Speech recognition services are not available](https://developer.apple.com/documentation/speech/sfspeechrecognizer/1649885-isavailable) for that device or at that moment.
