### ISSUE TITLE
Changing locale

### ISSUE THREAD

**Issue by johnjcamilleri** [alexruperez/SpeechRecognizerButton#6]
Great extension!

I want to change the language of voice recognition at runtime, but simply setting the `locale` property after I've done some SR in the first language doesn't seem to have an effect. Is there some function I can call to force a new `SFSpeechRecognizer` to be created with the new locale?

**Comment by johnjcamilleri** [comment]
Fixed this with a simple:

```swift
public var locale = Locale.autoupdatingCurrent {
    didSet {
        speechRecognizer = nil
    }
}
```

**Comment by johnjcamilleri** [comment]
After some more testing turns out this fix doesn't work. I'll fork and create a PR when I have a better solution.

**Comment by alexruperez** [comment]
Perfect, thanks for collaboration @johnjcamilleri

**Comment by johnjcamilleri** [comment]
Forgive the spam, my original solution does actually work. Was just something weird with Xcode, after cleaning things seemed to work again.

**Comment by alexruperez** [comment]
Don't worry, hehe, can be pull requested to the main repo or only cover your particular business case?

**Comment by johnjcamilleri** [comment]
I think the behaviour is very general and not specific to my use case, thus I have PR'd the changes.

**Comment by alexruperez** [comment]
Will be available on next release, thanks @johnjcamilleri!
